name: build-and-deploy

on:
  push:
    branches:
      - cli-test

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: build
        uses: actions/setup-node@v1
        with:
          node-version: '12'
          registry-url: https://registry.npm.taobao.org/
        run: yarn && yarn build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.repo }}
          publish_dir: ./dist
          publish_branch: gh-pages # default: gh-pages
  env:
    TZ: Asia/Shanghai
